'use client'

import { useEffect, useMemo, useState } from 'react'

import type { Translation } from '@/lib/types/database'
import type { SupportedLocale } from '@/contexts/LanguageContext'
import {
  deleteTranslation,
  getTranslationsByNamespaces,
  upsertTranslation
} from '@/lib/services/database'

const SUPPORTED_LOCALES: SupportedLocale[] = ['en', 'ka']

const emptyTranslation = (locale: SupportedLocale): Translation => ({
  id: '',
  namespace: '',
  key: '',
  locale,
  value: '',
  autoGenerated: false,
  updatedAt: new Date().toISOString()
})

export function TranslationsManager() {
  const [locale, setLocale] = useState<SupportedLocale>('en')
  const [namespaceFilter, setNamespaceFilter] = useState('')
  const [search, setSearch] = useState('')
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const [success, setSuccess] = useState('')
  const [translations, setTranslations] = useState<Translation[]>([])
  const [editing, setEditing] = useState<Translation | null>(null)
  const [saving, setSaving] = useState(false)

  const loadTranslations = async () => {
    setLoading(true)
    setError('')
    const namespaces = namespaceFilter.trim() ? [namespaceFilter.trim()] : []
    
    console.log(`[TranslationsManager] Loading translations for locale="${locale}" namespaces=${JSON.stringify(namespaces)}`)
    const { data, error } = await getTranslationsByNamespaces(namespaces, locale)
    console.log(`[TranslationsManager] Server returned ${data?.length ?? 0} translations, error:`, error)

    if (error) {
      console.error('Failed to load translations', error)
      setError('Unable to load translations. Please try again later.')
      setTranslations([])
    } else {
      setTranslations(data ?? [])
    }
    setLoading(false)
  }

  useEffect(() => {
    loadTranslations()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [locale])

  useEffect(() => {
    const timeout = setTimeout(() => {
      loadTranslations()
    }, 400)
    return () => clearTimeout(timeout)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [namespaceFilter])

  const filteredTranslations = useMemo(() => {
    if (!search.trim()) return translations
    const term = search.toLowerCase()
    return translations.filter((translation) =>
      translation.namespace.toLowerCase().includes(term) ||
      translation.key.toLowerCase().includes(term) ||
      translation.value.toLowerCase().includes(term)
    )
  }, [translations, search])

  const startEditing = (translation?: Translation) => {
    if (translation) {
      setEditing(translation)
    } else {
      setEditing(emptyTranslation(locale))
    }
    setSuccess('')
    setError('')
  }

  const handleChange = (field: keyof Translation, value: string | boolean) => {
    if (!editing) return
    setEditing({ ...editing, [field]: value })
  }

  const handleSave = async () => {
    if (!editing) return
    if (!editing.namespace.trim() || !editing.key.trim()) {
      setError('Namespace and key are required.')
      return
    }
    setSaving(true)
    setError('')
    const payload = {
      id: editing.id || undefined,
      namespace: editing.namespace.trim(),
      key: editing.key.trim(),
      locale: editing.locale,
      value: editing.value,
      autoGenerated: editing.autoGenerated
    }

    const { data, error } = await upsertTranslation(payload)
    if (error || !data) {
      console.error('Failed to save translation', error)
      setError('Failed to save translation.')
    } else {
      setSuccess('Translation saved successfully!')
      setEditing(null)
      setTranslations((prev) => {
        const exists = prev.find((item) => item.id === data.id)
        if (exists) {
          return prev.map((item) => (item.id === data.id ? data : item))
        }
        return [data, ...prev]
      })
    }
    setSaving(false)
  }

  const handleDelete = async (translation: Translation) => {
    if (!translation.id) return
    const confirmed = window.confirm(`Delete translation ${translation.namespace}.${translation.key}?`)
    if (!confirmed) return
    setSaving(true)
    const { error } = await deleteTranslation(translation.id)
    if (error) {
      console.error('Failed to delete translation', error)
      setError('Failed to delete translation.')
    } else {
      setTranslations((prev) => prev.filter((item) => item.id !== translation.id))
      if (editing?.id === translation.id) {
        setEditing(null)
      }
    }
    setSaving(false)
  }

  const namespaces = useMemo(() => {
    const set = new Set<string>()
    translations.forEach((translation) => set.add(translation.namespace))
    return Array.from(set).sort()
  }, [translations])

  return (
    <div className="w-full max-w-6xl mx-auto space-y-6">
      <div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between">
        <div className="flex flex-col gap-2 md:flex-row md:items-end">
          <div>
            <label className="block text-sm font-medium mb-1">Locale</label>
            <select
              className="w-full md:w-40 border rounded-md px-3 py-2"
              value={locale}
              onChange={(event) => {
                const nextLocale = event.target.value as SupportedLocale
                setLocale(nextLocale)
                setEditing((current) => current ? { ...current, locale: nextLocale } : current)
              }}
            >
              {SUPPORTED_LOCALES.map((option) => (
                <option key={option} value={option}>
                  {option.toUpperCase()}
                </option>
              ))}
            </select>
          </div>
          <div>
            <label className="block text-sm font-medium mb-1">Namespace</label>
            <input
              type="text"
              className="w-full md:w-48 border rounded-md px-3 py-2"
              placeholder="e.g., auth"
              value={namespaceFilter}
              onChange={(event) => setNamespaceFilter(event.target.value)}
            />
          </div>
          <div>
            <label className="block text-sm font-medium mb-1">Search</label>
            <input
              type="text"
              className="w-full md:w-64 border rounded-md px-3 py-2"
              placeholder="Search key or value"
              value={search}
              onChange={(event) => setSearch(event.target.value)}
            />
          </div>
        </div>
        <div className="flex gap-2">
          <button
            className="px-4 py-2 border rounded-md"
            onClick={loadTranslations}
            disabled={loading}
          >
            {loading ? 'Refreshing…' : 'Refresh'}
          </button>
          <button
            className="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700"
            onClick={() => startEditing()}
          >
            Add Translation
          </button>
        </div>
      </div>

      {error && <div className="p-3 rounded-md bg-red-50 text-red-700">{error}</div>}
      {success && <div className="p-3 rounded-md bg-green-50 text-green-700">{success}</div>}

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="lg:col-span-2 bg-white rounded-lg shadow divide-y">
          <div className="px-4 py-3 flex justify-between items-center">
            <h2 className="text-lg font-semibold">Translations ({filteredTranslations.length})</h2>
            <span className="text-sm text-gray-500">Namespaces: {namespaces.length || '—'}</span>
          </div>
          <div className="max-h-[600px] overflow-y-auto">
            {loading ? (
              <div className="p-6 text-center text-gray-500">Loading translations…</div>
            ) : filteredTranslations.length === 0 ? (
              <div className="p-6 text-center text-gray-500">No translations found.</div>
            ) : (
              <table className="min-w-full divide-y">
                <thead className="bg-gray-50">
                  <tr>
                    <th className="px-4 py-2 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider">Namespace</th>
                    <th className="px-4 py-2 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider">Key</th>
                    <th className="px-4 py-2 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider">Value</th>
                    <th className="px-4 py-2"></th>
                  </tr>
                </thead>
                <tbody className="divide-y">
                  {filteredTranslations.map((translation) => (
                    <tr key={translation.id || `${translation.namespace}-${translation.key}-${translation.locale}`}>
                      <td className="px-4 py-2 text-sm text-gray-600">{translation.namespace}</td>
                      <td className="px-4 py-2 text-sm font-medium text-gray-900">{translation.key}</td>
                      <td className="px-4 py-2 text-sm text-gray-700 line-clamp-2">{translation.value}</td>
                      <td className="px-4 py-2 text-right text-sm">
                        <button
                          className="text-blue-600 hover:underline mr-3"
                          onClick={() => startEditing(translation)}
                        >
                          Edit
                        </button>
                        {translation.id && (
                          <button
                            className="text-red-600 hover:underline"
                            onClick={() => handleDelete(translation)}
                          >
                            Delete
                          </button>
                        )}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            )}
          </div>
        </div>

        <div className="bg-white rounded-lg shadow p-6">
          <h2 className="text-lg font-semibold mb-4">{editing ? 'Edit translation' : 'Create translation'}</h2>
          {editing ? (
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium mb-1">Locale</label>
                <select
                  className="w-full border rounded-md px-3 py-2"
                  value={editing.locale}
                  onChange={(event) => handleChange('locale', event.target.value as SupportedLocale)}
                >
                  {SUPPORTED_LOCALES.map((option) => (
                    <option key={option} value={option}>
                      {option.toUpperCase()}
                    </option>
                  ))}
                </select>
              </div>
              <div>
                <label className="block text-sm font-medium mb-1">Namespace</label>
                <input
                  type="text"
                  className="w-full border rounded-md px-3 py-2"
                  value={editing.namespace}
                  onChange={(event) => handleChange('namespace', event.target.value)}
                  placeholder="e.g., auth"
                />
              </div>
              <div>
                <label className="block text-sm font-medium mb-1">Key</label>
                <input
                  type="text"
                  className="w-full border rounded-md px-3 py-2"
                  value={editing.key}
                  onChange={(event) => handleChange('key', event.target.value)}
                  placeholder="e.g., login.title"
                />
              </div>
              <div>
                <label className="block text-sm font-medium mb-1">Value</label>
                <textarea
                  className="w-full border rounded-md px-3 py-2"
                  rows={4}
                  value={editing.value}
                  onChange={(event) => handleChange('value', event.target.value)}
                />
              </div>
              <div className="flex items-center gap-2">
                <input
                  id="auto-generated"
                  type="checkbox"
                  checked={editing.autoGenerated}
                  onChange={(event) => handleChange('autoGenerated', event.target.checked)}
                />
                <label htmlFor="auto-generated" className="text-sm text-gray-600">
                  Mark as auto generated
                </label>
              </div>
              <div className="flex gap-3">
                <button
                  className="flex-1 px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 disabled:opacity-50"
                  onClick={handleSave}
                  disabled={saving}
                >
                  {saving ? 'Saving…' : 'Save'}
                </button>
                <button
                  className="px-4 py-2 border rounded-md"
                  onClick={() => setEditing(null)}
                >
                  Cancel
                </button>
              </div>
            </div>
          ) : (
            <div className="text-sm text-gray-500">
              Select a translation to edit it or create a new entry.
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
