// Database Types for Mentoring Platform
// Generated from Supabase schema

export type UserRole = 'coordinator' | 'mentor' | 'mentee'
export type PairingStatus = 'active' | 'completed' | 'paused' | 'pending'
export type SessionStatus = 'scheduled' | 'confirmed' | 'in-progress' | 'completed' | 'cancelled' | 'no-show'
export type SessionType = 'regular' | 'assessment' | 'goal-setting' | 'review'
export type SessionMode = 'virtual' | 'in-person' | 'phone'
export type AssessmentType = 'baseline' | 'progress' | 'final'
export type AssessmentStatus = 'draft' | 'active' | 'completed'
export type GoalStatus = 'not-started' | 'in-progress' | 'completed' | 'on-hold'
export type GoalPriority = 'low' | 'medium' | 'high'
export type ResourceType = 'document' | 'video' | 'link' | 'image' | 'presentation' | 'code'
export type ProgressEntryType = 'milestone' | 'reflection' | 'feedback' | 'achievement'
export type ProgressVisibility = 'private' | 'mentor' | 'public'
export type NotificationType = 'session_reminder' | 'new_message' | 'goal_update' | 'assessment_due' | 'system'
export type NotificationPriority = 'low' | 'medium' | 'high'
export type MessageType = 'direct' | 'session_note' | 'system'
export type ExperienceLevel = 'beginner' | 'intermediate' | 'advanced'

export interface Milestone {
  id: string;
  title: string;
  status: 'pending' | 'completed';
  target_date?: string;
}

export interface SessionEvaluation {
  id: string
  session_id: string
  pairing_id: string
  mentor_id: string
  mentee_id: string
  rating: number
  comment?: string
  resource_ids?: string[]
  created_at: string
}

export interface SessionEvaluation {
  id: string
  session_id: string
  pairing_id: string
  mentor_id: string
  mentee_id: string
  rating: number
  comment?: string
  resource_ids?: string[]
  created_at: string
}

export interface SystemSettingsRow {
  id: string
  enable_email_notifications: boolean
  allow_public_registration: boolean
  default_user_role: UserRole
  default_language: 'en' | 'ka'
  created_at: string
  updated_at: string
}

export interface SystemSettings {
  id: string
  enableEmailNotifications: boolean
  allowPublicRegistration: boolean
  defaultUserRole: UserRole
  defaultLanguage: 'en' | 'ka'
}

export interface TranslationRow {
  id: string
  namespace: string
  translation_key: string
  locale: string
  value: string
  auto_generated: boolean
  updated_by?: string | null
  updated_at: string
}

export interface Translation {
  id: string
  namespace: string
  key: string
  locale: string
  value: string
  autoGenerated: boolean
  updatedBy?: string
  updatedAt: string
}

// Database Tables
export interface User {
  id: string
  email: string
  full_name?: string
  role: UserRole
  region?: string
  locale?: string
  profile?: Record<string, unknown>
  avatar_url?: string
  phone?: string
  timezone?: string
  active: boolean
  created_at: string
  updated_at: string
}

export interface Mentor {
  id: string
  region?: string
  bio?: string
  skills?: string[]
  expertise_areas?: string[]
  years_experience?: number
  max_mentees: number
  availability?: Record<string, unknown>
  linkedin_url?: string
  github_url?: string
  website_url?: string
  active: boolean
  created_at: string
}

export interface Mentee {
  id: string
  federation?: string
  years_experience: number
  career_goals?: string[]
  learning_objectives?: string[]
  baseline_assessment_id?: string
  current_level?: ExperienceLevel
  preferred_mentor_skills?: string[]
  active: boolean
  created_at: string
}

export interface Client {
  id: string
  mentee_id: string
  display_name: string
  address?: string
  services_provided?: string
  active: boolean
  created_at: string
  updated_at: string
}

export interface ClientVisit {
  id: string
  mentee_id: string
  client_id: string
  title: string
  description?: string
  scheduled_at: string
  duration_minutes: number
  status: 'scheduled' | 'completed' | 'cancelled'
  created_at: string
  updated_at: string
}

export type ClientVisitEvaluationRating = number

export interface ClientVisitEvaluation {
  id: string
  visit_id: string
  mentee_id: string
  rating: ClientVisitEvaluationRating
  comment?: string
  resource_ids?: string[]
  created_at: string
}

export interface Pairing {
  id: string
  mentor_id: string
  mentee_id: string
  coordinator_id?: string
  status: PairingStatus
  start_date?: string
  end_date?: string
  goals?: string[]
  notes?: string
  created_at: string
  updated_at: string
}

export interface Session {
  id: string
  pairing_id: string
  mentor_id: string
  mentee_id: string
  mentee_ids?: string[]
  goal_id?: string
  title: string
  description?: string
  scheduled_at: string
  duration_minutes: number
  session_type?: SessionType
  mode: SessionMode
  meeting_link?: string
  meeting_password?: string
  topics?: string[]
  agenda?: string
  notes?: string
  mentor_feedback?: string
  mentee_feedback?: string
  rating?: number
  status: SessionStatus
  reminder_sent: boolean
  created_at: string
  updated_at: string
}

export interface Assessment {
  id: string
  mentee_id: string
  mentor_id?: string
  assessment_type: AssessmentType
  title: string
  questions: Record<string, unknown>
  responses?: Record<string, unknown>
  score?: number
  max_score?: number
  feedback?: string
  completed_at?: string
  status: AssessmentStatus
  created_at: string
}

export interface Goal {
  id: string
  pairing_id: string
  mentee_id: string
  title: string
  description?: string
  category?: string
  target_date?: string
  priority: GoalPriority
  status: GoalStatus
  progress_percentage: number
  milestones?: Milestone[]
  created_at: string
  updated_at: string
}

export interface Resource {
  id: string
  uploaded_by: string
  pairing_id?: string
  session_id?: string
  title: string
  description?: string
  resource_type: ResourceType
  file_path?: string
  file_url?: string
  file_name?: string
  file_size?: number
  mime_type?: string
  external_url?: string
  tags?: string[]
  is_public: boolean
  download_count: number
  created_at: string
}

export interface ProgressEntry {
  id: string
  pairing_id: string
  mentee_id: string
  mentor_id: string
  session_id?: string
  goal_id?: string
  entry_type: ProgressEntryType
  title: string
  content?: string
  metrics?: Record<string, unknown>
  attachments?: string[]
  visibility: ProgressVisibility
  created_at: string
}

export interface Notification {
  id: string
  user_id: string
  title: string
  message: string
  notification_type: NotificationType
  related_id?: string
  related_type?: string
  read_at?: string
  action_url?: string
  priority: NotificationPriority
  created_at: string
}

export interface Message {
  id: string
  pairing_id: string
  sender_id: string
  recipient_id: string
  subject?: string
  content: string
  message_type: MessageType
  attachments?: string[]
  read_at?: string
  replied_to?: string
  created_at: string
}

// Extended types with relations
export interface UserWithRole extends User {
  mentor?: Mentor
  mentee?: Mentee
}

export interface ClientWithVisits extends Client {
  visits?: ClientVisit[]
}

export interface PairingWithUsers extends Pairing {
  mentor: User
  mentee: User
  coordinator?: User
}

export interface SessionWithUsers extends Session {
  mentor: User
  mentee: User
  mentees?: User[]
  pairing: Pairing
  goal?: Goal | null
}

export interface GoalWithProgress extends Goal {
  progress_entries: ProgressEntry[]
}

// API Response types
export interface MenteeProgress {
  total_goals: number
  completed_goals: number
  goal_completion_rate: number
  total_sessions: number
  completed_sessions: number
  session_attendance_rate: number
}

export interface MentorStats {
  active_mentees: number
  total_sessions: number
  upcoming_sessions: number
}

export interface PlatformAnalytics {
  totalUsers: number;
  totalMentors: number;
  totalMentees: number;
  activePairings: number;
  sessionsThisMonth: number;
  averageSessionRating: number;
}

// Form types
export interface CreateUserForm {
  email: string
  full_name: string
  role: UserRole
  region?: string
  phone?: string
}

export interface CreateMentorForm extends CreateUserForm {
  bio?: string
  skills?: string[]
  expertise_areas?: string[]
  years_experience?: number
  linkedin_url?: string
  github_url?: string
  website_url?: string
}

export interface CreateMenteeForm extends CreateUserForm {
  federation?: string
  years_experience?: number
  career_goals?: string[]
  learning_objectives?: string[]
  current_level?: ExperienceLevel
}

export interface CreateSessionForm {
  pairing_id?: string
  mentor_id?: string
  mentee_id?: string
  mentee_ids?: string[]
  title: string
  description?: string
  scheduled_at: string
  duration_minutes?: number
  session_type?: SessionType
  mode?: SessionMode
  meeting_link?: string
  topics?: string[]
  agenda?: string
  goal_id?: string
}

export interface CreateGoalForm {
  pairing_id: string
  title: string
  description?: string
  category?: string
  target_date?: string
  priority?: GoalPriority
  status?: GoalStatus
  mentee_id?: string
}

export interface CreateClientForm {
  display_name: string
  address?: string
  services_provided?: string
}

export interface UpdateClientForm extends Partial<CreateClientForm> {
  active?: boolean
}

export interface CreateClientVisitForm {
  client_id: string
  title: string
  description?: string
  scheduled_at: string
  duration_minutes?: number
}

export interface UpdateClientVisitForm {
  client_id?: string
  title?: string
  description?: string
  scheduled_at?: string
  duration_minutes?: number
  status?: ClientVisit['status']
}

export interface CreateClientVisitEvaluationForm {
  rating: ClientVisitEvaluationRating
  comment?: string
  resource_ids?: string[]
}

export interface CreateSessionEvaluationForm {
  session_id: string
  pairing_id: string
  mentor_id: string
  mentee_id: string
  rating: number
  comment?: string
  resource_ids?: string[]
}

export interface CreateSessionEvaluationForm {
  session_id: string
  pairing_id: string
  mentor_id: string
  mentee_id: string
  rating: number
  comment?: string
  resource_ids?: string[]
}

// Database function return types
export type DatabaseFunction<T = unknown> = {
  data: T | null
  error: Error | null
}
